spring:
  application:
    name: assessment
  datasource:
    url: jdbc:mysql:localhost:3306/slabcode_db
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 600000 # 10 minutes duration by default: 10 minutes * 60 seconds * 1000 miliseconds
